### ISSUE TITLE
The file paths aren't enclosed in quotes ""

### ISSUE THREAD

**Issue by andrej-szontagh** [krakowski/gradle-jextract#12]
# Environment

  * JDK version: 19
  * Gradle version: 7.6
  * `gradle-jextract` version: 0.3.0
  * Operating system: Windows 10
  
# How does this bug occur?

Configure the build.gradle according the README.md 
and run the build.

# What happens when the bug occurs?

Build fails with the error saying that it got 5 headers instead of 1.

In short my folder names contains spaces so when you put such 
paths onto the command line it will obviously not work since the 
spaces are used as an argument separator. Adding quotes fixes the issue. 
The quotes should be there by default to support all different 
file paths including ones that have spaces in it.

# Would you like to submit a PR fixing this bug?
  
  [X] **YES**
  [ ] **NO**

**Comment by krakowski** [comment]
Hi @andrej-szontagh,

good catch! I think adding a [Extension function](https://kotlinlang.org/docs/extensions.html#extension-functions) on the `String` type (e.q. `quote`) and calling it at the appropriate locations ([includes](https://github.com/krakowski/gradle-jextract/blob/master/src/main/kotlin/io/github/krakowski/jextract/JextractTask.kt#L141), [output](https://github.com/krakowski/gradle-jextract/blob/master/src/main/kotlin/io/github/krakowski/jextract/JextractTask.kt#L165), and [header](https://github.com/krakowski/gradle-jextract/blob/master/src/main/kotlin/io/github/krakowski/jextract/JextractTask.kt#L167)) should do the job here. Feel free to submit a PR :slightly_smiling_face:

**Comment by andrej-szontagh** [comment]
Hi @krakowski,

Thank you for the reply! 

I was trying to get my hands on the JDK19 Panama features for my project and so far it was almost a week of struggle to build everything and make it work. Since I couldn't run the jextract.bat I was thinking about building an exe file however there were still some issues and even that I hate giving up it's just not worth my time. 

I had these two issues that I have submitted (the other one is also me). The thing is I am not versed in Kotlin and I also don't have any experience building Gradle plugins, seems like a lot of things are involved that's why I decided to try to make the exe. I also had this issue with not quoting the file paths.

So for now I decided to ditch the plugin and write it in my Gradle build script directly but it's unbelievable how I always hit some new problem that is in the way. (Windows 'cmd' is also stripping quotes for some reason).

Sorry for asking a dumb question, but I am not very good with abbreviations. I assume you want me to submit the change to the codebase?

**Comment by krakowski** [comment]
Hi @andrej-szontagh,

I thought you wanted to submit a pull request (PR) for this issue because you checked `[X] YES` under the issue's last question :smile: Since only minor changes were necessary, I just fixed the bugs quickly with https://github.com/krakowski/gradle-jextract/commit/354f9d218059c91b9715eb44976182a4dea554bd (published as version `0.3.1`) :slightly_smiling_face:

The issue was that I used a deprecated method for starting processes ([`Runtime#exec(String)`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String))):

  > __Deprecated.__
  > This method is error-prone and should not be used, the corresponding method [exec(String[])](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Runtime.html#exec(java.lang.String%5B%5D)) or [ProcessBuilder](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/ProcessBuilder.html) should be used instead. The command string is broken into tokens using only whitespace characters. For an argument with an embedded space, such as a filename, this can cause problems as the token does not include the full filename.

If you have the time: Can you clone the example repository https://github.com/krakowski/jextract-demo and try to run it?

```
git clone git@github.com:krakowski/jextract-demo.git
cd jextract-demo
gradlew.bat run
```

If everything works well you should see `Hello World` (printed using the native `printf` function).

**Comment by andrej-szontagh** [comment]
Hi @krakowski,

Thank you for the explanation, I rarely report bugs on GitHub :)
Also thank you very much for the fix! Can't wait to try it out.
I will let you know if the demo passed out correctly.

**Comment by andrej-szontagh** [comment]
> If you have the time: Can you clone the example repository https://github.com/krakowski/jextract-demo and try to run it?
> 
> ```
> git clone git@github.com:krakowski/jextract-demo.git
> cd jextract-demo
> gradlew.bat run
> ```
> 
> If everything works well you should see `Hello World` (printed using the native `printf` function).

So I have cloned the repo, however my whole system is setup to use JDK19 so I had to use gradle-7.6-20220924231105+0000-bin.zip

After running the build, the script couldn't find "stdc++" in my PATH. Not sure what to look for.

Exception in thread "main" java.lang.UnsatisfiedLinkError: no stdc++ in java.library.path: <PATH>
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2045)
        at org.unix.RuntimeHelper.<clinit>(RuntimeHelper.java:40)
        at org.unix.constants$0.<clinit>(constants$0.java:15)
        at org.unix.Linux.printf$MH(Linux.java:22)
        at org.unix.Linux.printf(Linux.java:25)
        at io.github.krakowski.NativeHelloWorld.print(NativeHelloWorld.java:18)
        at io.github.krakowski.NativeHelloWorld.main(NativeHelloWorld.java:10)

**Comment by krakowski** [comment]
Hey,

seems I missed your last update regarding the runtime error, sorry!

The error you get simply tells you that the specified library (`stdc++`) does not exist on the host system (in your case Windows). As this is not an error generated by this plugin and the example code runs fine (until the `printf` function is called),  I will close this issue for now. Feel free to create a new one if you encounter any other problems :slightly_smiling_face:
