### ISSUE TITLE
Update the plugin to support latest `jextract` 

### ISSUE THREAD

**Issue by sureshg** [krakowski/gradle-jextract#15]
Thanks for developing this plugin. As of OpenJDK 20 jextract, macro option is removed and throws the following error

```
> Invoking jextract failed.

   command: [Ljava.lang.String;@9b0b0e2
   stdout:
   stderr: OPTION ERROR: invalid option: --include-macro
  Usage: jextract <options> <header file>
  Use --help for a list of possible options

```

Also  missing the constants option in plugin.

```
--include-constant <name>          name of macro or enum constant to include
```

**Comment by krakowski** [comment]
Hey @sureshg,

thanks for pointing this out and your interest in this project! I just pushed version `0.4.0`, which is compatible with JDK 20 and should fix this problem. It seems the `--include-macro` option was simply renamed to `--include-constant`.

Could you please try it out and report if its working? :slightly_smiling_face:

**Comment by sureshg** [comment]
Awesome..thanks for the quick fix. It's working as expected now 👍🏼

**Comment by sureshg** [comment]
By the way, few more FFM API changes are landing on the 3rd preview -https://github.com/openjdk/jdk/pull/13079  ...jfyi
