### ISSUE TITLE
Command string not printed on failed build

### ISSUE THREAD

**Issue by tlf30** [krakowski/gradle-jextract#16]
# Environment

  * JDK version: 20
  * Gradle version: 8.0
  * `gradle-jextract` version: 0.4.0
  * Operating system: Win 11
  
# How does this bug occur?

When a jextract build fails

# What happens when the bug occurs?

The command string is not printed.

```
Invoking jextract failed.
  
   command: [Ljava.lang.String;@6d00ed1b
   stdout: 
   stderr: WARNING: A restricted method in java.lang.foreign.ValueLayout$OfAddress has been called
  WARNING: java.lang.foreign.ValueLayout$OfAddress::asUnbounded has been called by module org.openjdk.jextract
  WARNING: Use --enable-native-access=org.openjdk.jextract to avoid a warning for this module
```

# Would you like to submit a PR fixing this bug?
  
  [ ] **YES**
  [x] **NO**

**Comment by krakowski** [comment]
Hi @tlf30,

thanks for reporting this issue! I am able to reproduce it.

This will be fixed in the next version `0.4.1`.
