### ISSUE TITLE
jextract no longer supports "--source"

### ISSUE THREAD

**Issue by epkugelmass** [krakowski/gradle-jextract#21]
https://cr.openjdk.org/~mcimadamore/panama/jextract_changes.html

See
https://github.com/krakowski/gradle-jextract/blob/2fbc5180ad034b88df17860ee0b5f3881c9821e8/src/main/kotlin/io/github/krakowski/jextract/JextractTask.kt#L33
https://github.com/krakowski/gradle-jextract/blob/2fbc5180ad034b88df17860ee0b5f3881c9821e8/src/main/kotlin/io/github/krakowski/jextract/JextractTask.kt#L96

# Environment

  * JDK version: 22.0.0.0
  * Gradle version: 8.7
  * `gradle-jextract` version: 0.4.2
  * Operating system: Linux x64
  * jextract: 22-jextract+3-13 (2024/2/21)
  
# How does this bug occur?

Using the jextract plugin with default settings (`source = true`)

# What happens when the bug occurs?

```
.../jextract-bin/jextract-22/bin/java -m org.openjdk.jextract/org.openjdk.jextract.JextractTool --source -l lib --target-package com.lib --header-class-name Lib --output .../build/generated/sources/jextract/main/java .../lib.h
  ERROR: invalid option: --source
  Usage: jextract <options> <header file>
  Use --help for a list of possible options
```

# Would you like to submit a PR fixing this bug?
  
  [ ] **YES**
  [X] **NO**

**Comment by FlysoftBeta** [comment]
Just turn off source mode by `sourceMode = false`.
