### ISSUE TITLE
Is there a way to add the task without trying to run it?

### ISSUE THREAD

**Issue by sixcorners** [krakowski/gradle-jextract#25]
I want to have this plugin in my gradle build configured and ready to go if I need to regenerate the java bindings but I don't really want to run it every time. Is there a way to configure jextract as a task and make it available to be called on the command line but not have it squawk if jextract isn't found or try to run it?

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by krakowski** [comment]
This plugin already exposes the `jextract` task which you can modify inside your build script.

If you do not want the task to run, you could disable it using `jextract.enabled = false` inside your build script. Alternatively, you could disable/skip this task per build using `gradle build -x jextract`. If you want to call the task separately, you can use `gradle jextract`. Is this what you are looking for?

Also, the `jextract` task will only be executed if its input or output files have changed, which means it should not regenerate the bindings on each invocation.
